# API -> .env

# Notion
notion:
  content_file: "notion-api/notion_contents.json"

# Embedding settings
embedding:
  model: all-mpnet-base-v2  # all-MiniLM-L12-v2, all-mpnet-base-v2, all-distilroberta-v1 etc
  chunk_size: 1024
  overlap: 100
  db_dir: ./chroma_db 

# LLM settings
llm:
  model: mistralai/Mistral-7B-Instruct-v0.2 # google/gemma-2b-it, mistralai/Mistral-7B-Instruct-v0.2, openai-community/gpt2
  search_type: mmr          
  temperature: 0.4
  k: 4
  fetch_k: 20
  max_token: 1024

# Evaluation LLM settings
evaluation:
  max_workers: 2  # the best for my PC spec
  timeout: 600

